x = input('Digite algo: \n')
print('O tipo primitivo disso é', type(x))
print('É numérico?', x.isnumeric())
print('É alfabético?', x.isalpha())
print('É alfanumérico?', x.isalnum())
print('É maiúsculo?', x.isupper())
print('É espaço vazio?', x.isspace())
print('É minúsculo?', x.islower())
print('É decimal?', x.isdecimal())
